### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Twentysix26** [mrTownsend/mrTownsend-Cogs#1]
Hello there,
just a friendly reminder that licensing must be respected when working with open source.
From your README:
> "if any of you fellow devs see this and want a credit tag in the readme by all means ask"

> "But as I move further and further away from your original code base, your credit will eventually be removed."

This is not how licensing works. If you take someone else's work you *must* adhere to the original license's terms and even in the most permissive ones that means preserving the original license AND credits.
Repositories that don't do this get taken down on a regular basis so I suggest you to fix this as soon as possible.

**Comment by mrTownsend** [comment]
Hello there, Twentysix! Let me clarify for all PR - 

1.  I'm still **going to** place in here credit to the original creators, but I **will not be attributing any progress made on it to them** and **only** once **completely rewritten** will their credit tag be removed. Do you still say the plumber fixed your sink after you have to go back and do it again? No.  

2. My method of grabbing all of these repo's just to put them in one place was a very hack-job solution, and many files including licenses were not brought along. Solely the code that makes it function, that is it. Over the next coming days you will start to see them appear as I source them from the original author, as well as credit tags on the main module repository page. I am true to my word, I just realized that I didn't have the mental capacity at the time of writing said readme to go back and find all of those files. It was....4AM, more than likely and I was probably higher than a kite. 

3. If you have any further concerns please feel free to reply. I am not here trying to be a dickhead and rip other module owners. The RED community has a fantastic development base and there are many talented module owners and creators out there, and I'll be uploading my own originals as well. Many of the files have already had obvious changes to the authors and whatnot as I do prepare to make significant changes to them. You caught the painter before the paint was dry, I guess I could say.

Hope this clears any potential issues up. I'll be forwarding a copy of this to any collegues who reach out to me additionally. I am not here to create problems with you guys and once this is rectified I hope to continue to be an active contributor in the RED community. 

//C

**Comment by Twentysix26** [comment]
@mrTownsend 
From #10 
> I'm unable at this point to go back and figure out who owns what since many cogs on here are unlisted or unapproved and I can't find them due to the way Red's search works

Then the correct course of action here is to make the repository private (it takes **one** click) or delete it and remake it properly.
You're asking a lot of people to come here and help you rectify a problem you've created and I'm sorry but, again, this is not how licensing works.
It's not up to anyone but *you* to make sure that you're adhering to the license terms when you're making a new repository with someone else's content.
Your hand-waving approach to the situation is frankly quite grating. You act like giving credits and respecting licenses is a favor you're doing to people rather than the thing you're supposed to do.
You being "new" to GitHub (but apparently not too new to reupload content and giving credits to yourself for all of it) is not an excuse after plenty of people have been telling you that what you're doing is not ok.

I'm going to check back this repository and the other Red related ones you have in a couple of days, if they're not completely compliant with credits and licenses you are going to be banned from our community.
