### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Drapersniper** [mrTownsend/mrTownsend-Cogs#10]
So I'll be nice here...

1. why did you use someone else's work without accreditation?
2. what makes you think you are able to relicense someone else's work under a different license without permission

Please fix these - and nothing more will come of this.

**Comment by Drapersniper** [comment]
To clarify - even if you rewrite the whole cog using someone else as a base you are not allowed to remove the original license and credits

**Comment by mrTownsend** [comment]
Hey draper! Thanks for reaching out! I've explained this on many issues before but I'll fill you in. 

1. When I grabbed these cog folders, I didn't grab the host folder that contained the licenses and whatnot, I grabbed just the main cog folder. The other files never showed up. Thus, they are **all** missing. **AT THE SAME TIME...**
2. In preparation for my changes, I modified my own internal versions to my authorship and reset the version numbers to `0.0.1`, as I was going to be doing my own update increment logging. 

Both of these things happening at the same time gave the impression I was attempting to rip off multiple developers. This truly isn't the case. 

I'm unable at this point to go back and figure out who owns what since many cogs on here are unlisted or unapproved and I can't find them due to the way Red's search works, **but** if you see a cog in this repository that belongs to you or a friend, please let me know which module and which developer it belongs to so I can go grab said proper license files and add them along with their credits back.

**Comment by Drapersniper** [comment]
Cog [botstats](https://github.com/mrTownsend/mrTownsend-Cogs/tree/main/botstats)
Original License - [Unlicensed[(https://choosealicense.com/no-permission/)
> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.


Cog [account](https://github.com/mrTownsend/mrTownsend-Cogs/tree/main/account)
Original License - [GNU General Public License v3.0](https://github.com/Malarne/discord_cogs/blob/master/LICENSE)
Under section 5 - 
>     a) The work must carry prominent notices stating that you modified
>       it, and giving a relevant date.
>     b) The work must carry prominent notices stating that it is
>       released under this License and any conditions added under section
>       7.  This requirement modifies the requirement in section 4 to
>       "keep intact all notices".
>     c) You must license the entire work, as a whole, under this
>       License to anyone who comes into possession of a copy.  This
>       License will therefore apply, along with any applicable section 7
>       additional terms, to the whole of the work, and all its parts,
>       regardless of how they are packaged.  This License gives no
>       permission to license the work in any other way, but it does not
>       invalidate such permission if you have separately received it.
>     d) If the work has interactive user interfaces, each must display
>       Appropriate Legal Notices; however, if the Program has interactive
>       interfaces that do not display Appropriate Legal Notices, your
>       work need not make them do so.

Cog [userinfo](https://github.com/mrTownsend/mrTownsend-Cogs/tree/main/userinfo)
Original License - [MIT](https://github.com/flaree/flare-cogs/blob/master/LICENSE)

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.


These are just a few example of 3 easy license stats to get the original license for and they are just to serve a point, which is you are not allowed to do what you are doing and planning to do.

1 - It doesn't matter how it is done, people SHOULD not have to reach out to you because you are in breach of their license. Period.

2. your general interaction with others and states clearly shows your lack of understanding of how open-source software and licensing work.

> IF YOU ARE ONE OF THE DEVELOPERS WHOSE WORK IS LISTED HERE, CHILL OUT. READ THIS FIRST.

> I have no problem giving credit where it is due. Just don't hassle me if you abandoned the project publicly a long time ago.

> If any of you fellow devs see this and want a credit tag in the readme by all means ask. But as I move further and further away from your original code base, your credit will eventually be removed.

> I have no problem giving credit where it is due, until it is no longer due. I ask that before you ask however, you have updated the cog in question within the last 30 days.


The above states clearly shows that what you are attempting to do is claim someone else's work as yours

Actions such as  this commit clearly portray your intentions as if what you say is true, you wouldn't have to go out of your way to remove the credits in the first place.

> When I grabbed these cog folders, I didn't grab the host folder that contained the licenses and whatnot, I grabbed just the main cog folder. The other files never showed up. Thus, they are all missing. AT THE SAME TIME...

You are claiming that the info.json does come with the cogs and yet you got out of your way to remove the author and credits from it.

https://github.com/mrTownsend/mrTownsend-Cogs/commit/6d5cbb8ce70615d0737cdf5b896ac0e545d0a3e2#diff-dd10610da9daef21e9a404e89db4bba8c58175ac3e7ed8a7693634337b03d24c

**Comment by Drapersniper** [comment]
I will make this super simple for you.

I do not authorize any code I have written to belong in this repository due to its breach of several licenses.

Therefore I am officially requesting that any commit I have made for any of the cogs in this repository past, present, and future are permanently removed unless you come into compliance in full with every license for every piece of code here.

You have 7 days and if my request as code owner is not respected I shall DMCA this repository.

**Comment by mrTownsend** [comment]
What license would you like for botstats?

**Comment by Drapersniper** [comment]
None

**Comment by mrTownsend** [comment]
userinfo was previously resolved to flaree's satisfaction. 

account has a license attached to it. I'll be adding also a modification time to the about section to make it more transparent. 

as far as botstats, i'll remove it from the repo but I'm still going to privately maintain my own copy lmao. There's some developers who unlike you have reached out and used their heads. Pleasure talking to you.

**Comment by aikaterna** [comment]
Go ahead and block me too if you think that's the right move to make, but there's more to this
<img width="1062" alt="Screen Shot 2022-01-31 at 12 36 11 PM" src="https://user-images.githubusercontent.com/20862007/151869234-491cbda4-cc9f-4bf3-b48a-f42cb8f282dc.png">

**Comment by mrTownsend** [comment]
botstats has been removed from the repo and archived. Other people's licenses and shit are being added as I go thru it. I dont sit on my computer 24/7.
