### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by flaree** [mrTownsend/mrTownsend-Cogs#3]
Hi there,

I would like. all the respective attribution and licensing applied to any cog you may have taken from my repos.

**Comment by mrTownsend** [comment]
Hello there, flaree! Let me clarify for all PR - 

1.  I'm still **going to** place in here credit for cogs from your repositories. 

2. My method of grabbing all of these repo's just to put them in one place was a very hack-job solution, and many files including licenses were not brought along. Solely the code that makes it function, that is it. Over the next coming days you will start to see them appear as I source them from the original author, as well as credit tags on the main module repository page. I am true to my word, I just realized that I didn't have the mental capacity at the time of writing said readme to go back and find all of those files. It was....4AM, more than likely and I was probably higher than a kite. 

3. If you have any further concerns please feel free to reply. I am not here trying to be a dickhead and rip other module owners. The RED community has a fantastic development base and there are many talented module owners and creators out there, and I'll be uploading my own originals as well. Many of the files have already had obvious changes to the authors and whatnot as I do prepare to make significant changes to them. You caught the painter before the paint was dry, I guess I could say.

Hope this clears any potential issues up. I'll be forwarding a copy of this to any collegues who reach out to me additionally. I am not here to create problems with you guys and once this is rectified I hope to continue to be an active contributor in the RED community. 

//C

**Comment by mrTownsend** [comment]
Added LICENSE file for emailverification.py, formerly emailverify. Let me know if there is anything else I can do for you by opening another issue.

**Comment by flaree** [comment]
Hi there,

I noticed your addition of the license which I respect. There is also the case for the attribution. Specifically under the author field in the `info.json` under EmailVerify, along with the `__author__` attribute within the cog. This can be amended by adding my field that was there previously, along with yours following. `flare(flare#0001), mrTownsend` for example.

This must also be repeated in the Userinfo cog.

**Comment by mrTownsend** [comment]
Done! Thank you for not being an ass about it :)

Let me know if there's anything else I can do for you.
