### ISSUE TITLE
Stolen work

### ISSUE THREAD

**Issue by TrustyJAID** [mrTownsend/mrTownsend-Cogs#4]
Hello, it appears you have blatantly copied my cog, [Backup](https://github.com/TrustyJAID/Trusty-cogs/tree/master/backup), and changed the author in your [info.json](https://github.com/mrTownsend/mrTownsend-Cogs/blob/main/backup/info.json) without attributing me as the original author. This is proven by the fact that my current [info.json](https://github.com/TrustyJAID/Trusty-cogs/blob/master/backup/info.json) file has the cog hidden preventing it from being seen by Red's downloader which will be true for both your version and mine. You should not just claim you're the author of something when you aren't. If you have made modifications to my code you can add yourself to the author list as long as you also respect my codes [license.](https://github.com/TrustyJAID/Trusty-cogs/blob/master/LICENSE.txt)

**Comment by mrTownsend** [comment]
Hello there, TrustyJAID! Let me clarify for all PR -

I'm still going to place in here credit for cogs from your repositories.

My method of grabbing all of these repo's just to put them in one place was a very hack-job solution, and many files including licenses were not brought along. Solely the code that makes it function, that is it. Over the next coming days you will start to see them appear as I source them from the original author, as well as credit tags on the main module repository page. I am true to my word, I just realized that I didn't have the mental capacity at the time of writing said readme to go back and find all of those files. It was....4AM, more than likely and I was probably higher than a kite.

If you have any further concerns please feel free to reply. I am not here trying to be a dickhead and rip other module owners. The RED community has a fantastic development base and there are many talented module owners and creators out there, and I'll be uploading my own originals as well. Many of the files have already had obvious changes to the authors and whatnot as I do prepare to make significant changes to them. You caught the painter before the paint was dry, I guess I could say.

Hope this clears any potential issues up. I'll be forwarding a copy of this to any collegues who reach out to me additionally. I am not here to create problems with you guys and once this is rectified I hope to continue to be an active contributor in the RED community.

//C

**Comment by TrustyJAID** [comment]
You know, the time it has taken you to write this original response you could have started a commit to fix all these issues from people claiming stolen work or deleted the repo and started fresh from scratch not doing a "hack-job" solution to something that isn't even needed. What is the purpose of copying someone else's code into your own repo when you can fork someone else's repo and install that fork onto your bot. Or install that other users repo and receive updates from the original author? Especially since you haven't provided any updates to the original authors source except claiming you're the new author.

**Comment by mrTownsend** [comment]
1. You recieved a copy-paste like everybody else, actually saving me time so I could go add the licenses as issued were created instead of dealing with messages individually. I changed the name on every message to make the person reading it feel special. 

2. ![Image](https://i.imgur.com/cTUAk0g.png) ???????? Yes, I am terribly apologetic that in the span of five days I have not had time to completely rewrite every single cog already, I will try to do better in the future. 

You'll receive an update when your licensing is added.

**Comment by TrustyJAID** [comment]
1. I understand why you copy-pasted and that makes sense but I stated that original copy-pasted message you wrote took more time than just fixing the issue.
2. That is understandable I suppose and perhaps these other people are jumping the gun a bit but licensing is a very important thing in the programming world. Copying other people's work is a very serious offence and your first act on github should not be to copy someone else's work especially not like this. Again you're better off forking from someone else and if you have a worthwhile contribution to that person's stuff you can make a pull request which asks the original author to pull their fork in the direction you want to see.

I hope that you see I am not trying to attack you here just curious and hopefully you don't take this as a sign to not continue learning and working on code. There is a *right* way to do things and this approach is largely considered the *wrong* way.

**Comment by mrTownsend** [comment]
I've been doing Python development for close to 4 years now I've just always worked in private environments. This was deadass not how any of this was supposed to go and like, I'm glad that developers are hounds about their credit for work you know, I think its important, but this was the result of a technical error and it feels like a few more spankings than are due. Please let me know if there's anything I can do for you, no ill will <3
