### ISSUE TITLE
Additional requirements

### ISSUE THREAD

**Issue by flaree** [mrTownsend/mrTownsend-Cogs#6]
Hi there,

I noticed your addition of the license which I respect. There is also the case for the attribution. Specifically under the author field in the info.json under EmailVerify, along with the __author__ attribute within the cog. This can be amended by adding my field that was there previously, along with yours following. flare(flare#0001), mrTownsend for example.

This must also be repeated in the Userinfo cog.

Thank you

**Comment by mrTownsend** [comment]
These cogs have had this information changed in preparation for complete if not significant rewrites. I'll add as a co-author if you so wish. Will also attach license to userinfo, forgot that wasn't stock. 

Will receive an update once added.

**Comment by flaree** [comment]
Regardless of rewrites, I'm still the author of said code and thus must be respected

**Comment by mrTownsend** [comment]
LICENSE and author information in about added. Please open a new issue if there is anything else I can do for you.

**Comment by flaree** [comment]
Thank you! Sorry for the hassle.

**Comment by mrTownsend** [comment]
No no, you're perfectly fine. You weren't an ass to me and you didn't make a mistake a giant hassle. It was my problem to solve. Thank you for taking the time to reach out to me.
