### ISSUE TITLE
License and attribution

### ISSUE THREAD

**Issue by Vexed01** [mrTownsend/mrTownsend-Cogs#7]
Hi,

I have noticed that you have copied my `BetterUptime` and `StatTrack` cogs from my repository at https://github.com/Vexed01/Vex-Cogs. I am the original author of both of these. You have renamed the `BetterUptime` cog's folder to `Uptime`, though the cog class remains `BetterUptime`.

These cogs are licensed under GNU General Public License v3.0.

I am requesting that you add a copy of the GNU General Public License v3.0 license to both of these cogs.
I am also requesting that you re-add attribution to me (specifically `Vexed (Vexed#9000)`) to both of these cogs' `author` fields in the respective `info.json` files.
I am also requesting that you re-add attribution to me (specifically `Vexed#9000`) to the `__author__` field of the `BetterUptime` and `StatTrack` cog classes.

If you copy more of my cogs, please ensure you do not remove any attribution and keep the license.

**Comment by mrTownsend** [comment]
Thanks for reaching out! This has been ongoing fuckery today. TLDR as explained in other issues - I cloned the folders with the code, not the folders of the folders with it. Some files are MIA. Thank u for reaching out, I'll update this issue once credit has been added. Thank you for being cool <3

**Comment by mrTownsend** [comment]
Requested changes have been made. Thank you for being cool. Open a new issue if there's anything else I can do for you.

**Comment by Vexed01** [comment]
Thank you for such a swift response.

**Comment by mrTownsend** [comment]
There's a misconception between the developers who were summoned to create an issue here for their code that I was doing it to be a cunt to ya'll or something lmao it was a genuine mistake, I wanted to be quick in rectifying it. Thank you for being so cool about it. If there's anything I can do for you or help you with in the future pleeeeease open a new issue and I got you.
