### ISSUE TITLE
Still missing attribution

### ISSUE THREAD

**Issue by phenom4n4n** [mrTownsend/mrTownsend-Cogs#9]
I’m still missing attribution on a cog in this repository. I suggest you go through all the cogs on this repository and re-add the credit you removed.

**Comment by mrTownsend** [comment]
The only module I'm able to find by you is `disboard`. I've added your license, its actually in two places now, and there is a link on the main page. If there's anything else you need let me know.

**Comment by phenom4n4n** [comment]
I'm missing attribution on the decancer cog as a contributor, and the original author of that cog is as well. Also, you misspelled my name on the readme.

**Comment by mrTownsend** [comment]
Sorry about the mis-spell, my keyboard is like 6 years old and is progressively shitting the bed. 

Corrected README.md link, corrected decancer `info.json` with your attribution. 

LMK if this works.

**Comment by phenom4n4n** [comment]
In the source code of the original decancer cog, I'm listed as an author in the `__author__` attribute, not info.json. As I said, you're also missing credit towards the original author of that cog. Credit should be given when it's due, not on demand.

**Comment by mrTownsend** [comment]
I've already previously explained why the changes were made, I'm not justifying myself again. everybody has different workflows and preferences. Again, that's why I said in the readme to just let me know. 

Updated `decancer.py` to include your name. I'm not aware who the other author is, again, I explained what happened here

**Comment by phenom4n4n** [comment]
It's not my job to inform you on how to follow copyright, licensing, and attribution rules. I'm speaking on behalf of all cog creators from whom you re-distributed code when I say you need to re-add attribution, or face legal consequences.

**Comment by mrTownsend** [comment]
Have I made the sufficient updates? I'm confused.
